
<!--Menu - Drzewo 5 (menu_tree5, 80949.1)-->
{{capture name="setMenuGfx_menu_tree5" assign="setMenuGfx_menu_tree5"}}{{$txt['80949::set_menu_gfx_menu_tree5']}}{{/capture}}{{if  $xml->getItem("navigation5/item")}}
<div class="n57356_main">
<ul class="n57356_main">{{foreach from=$xml->getList("navigation5/item") item=loop8}}
<li>{{if  $loop8->getItem("@link")}}
<a{{assign "onmouseoutAttributeTmp1" ""}}  href="{{$loop8->getItemEscape("@link")}}" {{if $loop8->getItem("@target")}} target="{{$loop8->getItemEscape("@target")}}" {{/if}}{{if ( $loop8->getItem("@gfx") or $loop8->getItem("@gfx_active")) and $loop8->getItem("@gfx_onmouseover")}} onmouseover="$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx_onmouseover")}}');" {{if $loop8->getItem("@gfx_active")}}{{capture name="onmouseoutAttributeTmp1" assign="onmouseoutAttributeTmp1"}}$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx")}}');{{/capture}}{{else}}{{capture name="onmouseoutAttributeTmp1" assign="onmouseoutAttributeTmp1"}}$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx")}}');{{/capture}}{{/if}}{{/if}}  onmouseout="{{$onmouseoutAttributeTmp1}}">{{if  $loop8->getItem("@gfx") or  $loop8->getItem("@gfx_active")}}{{if $setMenuGfx_menu_tree5}}
<img alt="{{$loop8->getItem("@name")}}" {{if (( $loop8->getItem("@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni")))}} src="{{$loop8->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop8->getItemEscape("@gfx")}}" {{/if}}></img>
<span>{{$loop8->getItem("@name")}}</span>{{else}}
<img alt="{{$loop8->getItem("@name")}}" {{if (( $loop8->getItem("@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni")))}} src="{{$loop8->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop8->getItemEscape("@gfx")}}" {{/if}}></img>{{/if}}{{else}}{{$loop8->getItem("@name")}}{{/if}}</a>{{else}}
<span{{assign "onmouseoutAttributeTmp2" ""}}{{if ( $loop8->getItem("@gfx") or $loop8->getItem("@gfx_active")) and $loop8->getItem("@gfx_onmouseover")}} onmouseover="$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx_onmouseover")}}');" {{if $loop8->getItem("@gfx_active")}}{{capture name="onmouseoutAttributeTmp2" assign="onmouseoutAttributeTmp2"}}$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx")}}');{{/capture}}{{else}}{{capture name="onmouseoutAttributeTmp2" assign="onmouseoutAttributeTmp2"}}$(this).children('img').attr('src','{{$loop8->getItemEscape("@gfx")}}');{{/capture}}{{/if}}{{/if}}  onmouseout="{{$onmouseoutAttributeTmp2}}">{{if  $loop8->getItem("@gfx") or  $loop8->getItem("@gfx_active")}}{{if $setMenuGfx_menu_tree5}}
<img alt="{{$loop8->getItem("@name")}}" {{if (( $loop8->getItem("@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni")))}} src="{{$loop8->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop8->getItemEscape("@gfx")}}" {{/if}}></img>
<span>{{$loop8->getItem("@name")}}</span>{{else}}
<img alt="{{$loop8->getItem("@name")}}" {{if (( $loop8->getItem("@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni"))) or (( $loop8->getItem("item/item/item/@ni")) == (string) ( $loop8->getItem("/shop/navigation/current/@ni")))}} src="{{$loop8->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop8->getItemEscape("@gfx")}}" {{/if}}></img>{{/if}}{{else}}{{$loop8->getItem("@name")}}{{/if}}</span>{{/if}}{{if  $loop8->getItem("item")}}
<ul>{{foreach from=$loop8->getList("item") item=loop96}}
<li>{{if  $loop96->getItem("@link")}}
<a{{assign "onmouseoutAttributeTmp3" ""}}  href="{{$loop96->getItemEscape("@link")}}" {{if $loop96->getItem("@target")}} target="{{$loop96->getItemEscape("@target")}}" {{/if}}{{if ( $loop96->getItem("@gfx") or $loop96->getItem("@gfx_active")) and $loop96->getItem("@gfx_onmouseover")}} onmouseover="$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx_onmouseover")}}');" {{if $loop96->getItem("@gfx_active")}}{{capture name="onmouseoutAttributeTmp3" assign="onmouseoutAttributeTmp3"}}$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx")}}');{{/capture}}{{else}}{{capture name="onmouseoutAttributeTmp3" assign="onmouseoutAttributeTmp3"}}$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx")}}');{{/capture}}{{/if}}{{/if}}  onmouseout="{{$onmouseoutAttributeTmp3}}">{{if  $loop96->getItem("@gfx") or  $loop96->getItem("@gfx_active")}}{{if $setMenuGfx_menu_tree5}}
<img alt="{{$loop96->getItem("@name")}}" {{if (( $loop96->getItem("@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni")))}} src="{{$loop96->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop96->getItemEscape("@gfx")}}" {{/if}}></img>
<span>{{$loop96->getItem("@name")}}</span>{{else}}
<img alt="{{$loop96->getItem("@name")}}" {{if (( $loop96->getItem("@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni")))}} src="{{$loop96->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop96->getItemEscape("@gfx")}}" {{/if}}></img>{{/if}}{{else}}{{$loop96->getItem("@name")}}{{/if}}</a>{{else}}
<span{{assign "onmouseoutAttributeTmp4" ""}}{{if ( $loop96->getItem("@gfx") or $loop96->getItem("@gfx_active")) and $loop96->getItem("@gfx_onmouseover")}} onmouseover="$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx_onmouseover")}}');" {{if $loop96->getItem("@gfx_active")}}{{capture name="onmouseoutAttributeTmp4" assign="onmouseoutAttributeTmp4"}}$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx")}}');{{/capture}}{{else}}{{capture name="onmouseoutAttributeTmp4" assign="onmouseoutAttributeTmp4"}}$(this).children('img').attr('src','{{$loop96->getItemEscape("@gfx")}}');{{/capture}}{{/if}}{{/if}}  onmouseout="{{$onmouseoutAttributeTmp4}}">{{if  $loop96->getItem("@gfx") or  $loop96->getItem("@gfx_active")}}{{if $setMenuGfx_menu_tree5}}
<img alt="{{$loop96->getItem("@name")}}" {{if (( $loop96->getItem("@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni")))}} src="{{$loop96->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop96->getItemEscape("@gfx")}}" {{/if}}></img>
<span>{{$loop96->getItem("@name")}}</span>{{else}}
<img alt="{{$loop96->getItem("@name")}}" {{if (( $loop96->getItem("@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni"))) or (( $loop96->getItem("item/item/item/@ni")) == (string) ( $loop96->getItem("/shop/navigation/current/@ni")))}} src="{{$loop96->getItemEscape("@gfx_active")}}" {{else}} src="{{$loop96->getItemEscape("@gfx")}}" {{/if}}></img>{{/if}}{{else}}{{$loop96->getItem("@name")}}{{/if}}</span>{{/if}}</li>{{/foreach}}</ul>{{/if}}</li>{{/foreach}}</ul></div>{{/if}}
